[icons]
name = "awesome"

[icons.overrides]
cpu = ""

[[block]]
block = "net"

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0
#format = "{icon}{used}/{total} {unit} ({available}{unit} free)"

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_used}/{mem_total}({mem_used_percents})"
format_swap = "{swap_used}/{swap_total}({swap_used_percents})"

[[block]]
block = "cpu"
interval = 1
format = "{barchart} {frequency}"

[[block]]
block = "load"
format = "{1m} {5m}"
interval = 1

[[block]]
block = "time"
interval = 60
format = "%A %d. %b %Y %R"
